#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

# Hash one or more font header files into a signed 32-bit int.
hash_files() {
  ruby -rdigest -e \
    'puts ARGV.map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)' \
    "$@"
}

# Emit a reading-font ID define.
# When the noemoji/ directory exists, emits an #ifdef OMIT_EMOJI_FONTS block so
# the correct hash is selected at compile time.
# Usage: reading_font_id DEFINE_NAME file1 [file2 ...]
#   Files are relative paths from builtinFonts/ (e.g. ./lexenddeca_10_regular.h).
#   Noemoji counterparts are assumed to live at noemoji/<basename>.
reading_font_id() {
  local name="$1"; shift
  local files=("$@")

  if [ -d "./noemoji" ]; then
    local noemoji_files=()
    for f in "${files[@]}"; do
      noemoji_files+=("./noemoji/$(basename "$f")")
    done
    echo "#ifdef OMIT_EMOJI_FONTS"
    echo "#define ${name} ($(hash_files "${noemoji_files[@]}"))"
    echo "#else"
    echo "#define ${name} ($(hash_files "${files[@]}"))"
    echo "#endif"
  else
    echo "#define ${name} ($(hash_files "${files[@]}"))"
  fi
}

# Reading fonts - support OMIT_EMOJI_FONTS
reading_font_id LEXENDDECA_8_FONT_ID \
  ./lexenddeca_8_regular.h ./lexenddeca_8_bold.h ./lexenddeca_8_bolditalic.h ./lexenddeca_8_italic.h
reading_font_id LEXENDDECA_10_FONT_ID \
  ./lexenddeca_10_regular.h ./lexenddeca_10_bold.h ./lexenddeca_10_bolditalic.h ./lexenddeca_10_italic.h
reading_font_id LEXENDDECA_12_FONT_ID \
  ./lexenddeca_12_regular.h ./lexenddeca_12_bold.h ./lexenddeca_12_bolditalic.h ./lexenddeca_12_italic.h
reading_font_id LEXENDDECA_14_FONT_ID \
  ./lexenddeca_14_regular.h ./lexenddeca_14_bold.h ./lexenddeca_14_bolditalic.h ./lexenddeca_14_italic.h
reading_font_id LEXENDDECA_16_FONT_ID \
  ./lexenddeca_16_regular.h ./lexenddeca_16_bold.h ./lexenddeca_16_bolditalic.h ./lexenddeca_16_italic.h

reading_font_id BITTER_8_FONT_ID \
  ./bitter_8_regular.h ./bitter_8_bold.h ./bitter_8_bolditalic.h ./bitter_8_italic.h
reading_font_id BITTER_10_FONT_ID \
  ./bitter_10_regular.h ./bitter_10_bold.h ./bitter_10_bolditalic.h ./bitter_10_italic.h
reading_font_id BITTER_12_FONT_ID \
  ./bitter_12_regular.h ./bitter_12_bold.h ./bitter_12_bolditalic.h ./bitter_12_italic.h
reading_font_id BITTER_14_FONT_ID \
  ./bitter_14_regular.h ./bitter_14_bold.h ./bitter_14_bolditalic.h ./bitter_14_italic.h
reading_font_id BITTER_16_FONT_ID \
  ./bitter_16_regular.h ./bitter_16_bold.h ./bitter_16_bolditalic.h ./bitter_16_italic.h

# Quicksand reading font - single variant only (no emoji/PHM fallback faces
# baked in), so the reading_font_id helper's noemoji/ branch isn't needed.
echo "#define QUICKSAND_8_FONT_ID ($(hash_files ./quicksand_8_regular.h ./quicksand_8_bold.h ./quicksand_8_bolditalic.h ./quicksand_8_italic.h))"
echo "#define QUICKSAND_10_FONT_ID ($(hash_files ./quicksand_10_regular.h ./quicksand_10_bold.h ./quicksand_10_bolditalic.h ./quicksand_10_italic.h))"
echo "#define QUICKSAND_12_FONT_ID ($(hash_files ./quicksand_12_regular.h ./quicksand_12_bold.h ./quicksand_12_bolditalic.h ./quicksand_12_italic.h))"
echo "#define QUICKSAND_14_FONT_ID ($(hash_files ./quicksand_14_regular.h ./quicksand_14_bold.h ./quicksand_14_bolditalic.h ./quicksand_14_italic.h))"
echo "#define QUICKSAND_16_FONT_ID ($(hash_files ./quicksand_16_regular.h ./quicksand_16_bold.h ./quicksand_16_bolditalic.h ./quicksand_16_italic.h))"

# UI fonts — Quicksand SemiBold (regular slot) + Quicksand Bold (bold slot).
# Static fonts, no emoji/PHM/symbol fallback (UI text is short labels).
echo "#define UI_10_FONT_ID ($(hash_files ./quicksand_sb_10_regular.h ./quicksand_sb_10_bold.h))"
echo "#define UI_12_FONT_ID ($(hash_files ./quicksand_sb_12_regular.h ./quicksand_sb_12_bold.h))"
echo "#define SMALL_FONT_ID ($(hash_files ./quicksand_sb_8_regular.h))"

echo ""
echo "// Font ID 0 is reserved as the \"not found\" sentinel."
echo "// Guard against any hash accidentally producing 0."
for id in \
  LEXENDDECA_8_FONT_ID LEXENDDECA_10_FONT_ID LEXENDDECA_12_FONT_ID LEXENDDECA_14_FONT_ID LEXENDDECA_16_FONT_ID \
  BITTER_8_FONT_ID BITTER_10_FONT_ID BITTER_12_FONT_ID BITTER_14_FONT_ID BITTER_16_FONT_ID \
  QUICKSAND_8_FONT_ID QUICKSAND_10_FONT_ID QUICKSAND_12_FONT_ID QUICKSAND_14_FONT_ID QUICKSAND_16_FONT_ID \
  UI_10_FONT_ID UI_12_FONT_ID SMALL_FONT_ID; do
  echo "static_assert(${id} != 0, \"Font ID collision with sentinel\");"
done
