// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_10_FONT_ID (-1178760654)
#else
#define LEXENDDECA_10_FONT_ID (-833446840)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_12_FONT_ID (576453416)
#else
#define LEXENDDECA_12_FONT_ID (-1629698200)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_14_FONT_ID (-90104999)
#else
#define LEXENDDECA_14_FONT_ID (1797004611)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_16_FONT_ID (-1174553084)
#else
#define LEXENDDECA_16_FONT_ID (-654563150)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_10_FONT_ID (-1655643523)
#else
#define BITTER_10_FONT_ID (-2037991310)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_12_FONT_ID (-998701579)
#else
#define BITTER_12_FONT_ID (70596465)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_14_FONT_ID (-969934)
#else
#define BITTER_14_FONT_ID (1849723397)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_16_FONT_ID (-263078880)
#else
#define BITTER_16_FONT_ID (1209964980)
#endif
#define QUICKSAND_10_FONT_ID (391393583)
#define QUICKSAND_12_FONT_ID (-329322055)
#define QUICKSAND_14_FONT_ID (-86035046)
#define QUICKSAND_16_FONT_ID (-790538177)
#define UI_10_FONT_ID (517068175)
#define UI_12_FONT_ID (2015786853)
#define SMALL_FONT_ID (1309502782)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(LEXENDDECA_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(QUICKSAND_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(QUICKSAND_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(QUICKSAND_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(QUICKSAND_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
